### ISSUE TITLE
Can't Mock ConfigParser

### ISSUE THREAD

**Issue by davidkazuhiro** [dksh/jira-issue-closer#1]
When I run the unittests I get this

```
$ python3 -m nose
E
======================================================================
ERROR: test_config_basic (test_closer.TestCloser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/mock.py", line 1157, in patched
    return func(*args, **keywargs)
  File "/Users/david.somers-harris/git/ghe/gisid/jira-issue-closer/test_closer.py", line 9, in test_config_basic
    closer = Closer()
  File "/Users/david.somers-harris/git/ghe/gisid/jira-issue-closer/closer.py", line 10, in __init__
    print(self.config.items('jira'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/configparser.py", line 846, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'jira'
-------------------- >> begin captured stdout << ---------------------
[jira]
url = https://jira.test.com

<class 'str'>

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 0.027s

FAILED (errors=1)
```

But if I just instantiate the class without the mock, I get no error even though the data looks the same...
```
[jira]
url = https://jira.example.com

<class 'str'>
[('url', 'https://jira.example.com')]
```

**Comment by davidkazuhiro** [comment]
Gave up. will just change the way I pass configs and avoid mocking
